[theme]
base = "dark"
primaryColor = "#6366F1"
backgroundColor = "#09090B"
secondaryBackgroundColor = "#18181B"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
